config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  get 'search', to: "dashboard#search", as: "search"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :movie_actors
  has_many :movies, through: :movie_actors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movies
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :movies

  def to_s
    [name, country].join('-') 
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :movie_actors
  has_many :actors, through: :movie_actors
  has_many :reviews

  belongs_to :director

  has_many :movie_locations
  has_many :locations, through: :movie_locations
end

app/models/movie_actor.rb
class MovieActor < ApplicationRecord
  belongs_to :actor
  belongs_to :movie
end

app/models/movie_location.rb
class MovieLocation < ApplicationRecord
  belongs_to :movie
  belongs_to :location
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @movies = Movie.select('movies.*, AVG(reviews.star) AS average_star')
                  .joins(:reviews)
                  .group('movies.id')
                  .order('average_star DESC')
                  .includes(:actors, :locations, :director)

  end

  def search
    @actors = Actor.where("name ILIKE ?", "%#{params[:actor_name]}%")
                   .includes(:movies)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<h1>Movies</h1>
<p>Ordered by average stars</p>

<%= form_tag(search_path, method: "get") do %>
  <div class="field">
    <%= label_tag(:actor_name, "Actor Name:") %>
    <%= text_field_tag(:actor_name) %>
  </div>
  <%= submit_tag("Search") %>
<% end %>
<br>

<table border="1">
  <thead>
    <tr>
      <th>Movie Name</th>
      <th>Description</th>
      <th>Year</th>
      <th>Actors</th>
      <th>Locations</th>
      <th>Director</th>
      <th>Average Star</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.description %></td>
        <td><%= movie.year %></td>
        <td><%= movie.actors.map(&:name).join(', ') %></td>
        <td><%= movie.locations.map(&:to_s).join(', ') %></td>
        <td><%= movie.director.name %></td>
        <td><%= movie.average_star %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/search.html.erb
<h1>Actors</h1>
<p>search result</p>

<%= form_tag(search_path, method: "get") do %>
  <div class="field">
    <%= label_tag(:actor_name, "Actor Name:") %>
    <%= text_field_tag(:actor_name) %>
  </div>
  <%= submit_tag("Search") %>
<% end %>
<br>

<table border="1">
  <thead>
    <tr>
      <th>Actor Name</th>
      <th>Movies</th>
    </tr>
  </thead>
  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= actor.movies.map(&:name).join(', ') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>